// console.log(username);
console.log("Pramod is awesome");
console.log("Pramod is awesome");
console.log("Pramod is awesome");
console.log("Pramod is awesome");
let username = "Dutta";
console.log("Pramod is awesome");
console.log("Pramod is awesome");
console.log("Pramod is awesome");
console.log(username);
