let x = 10;
//x = x + 10;
x += 10; // --> //x = x + 10;
x -= 3; // x = x - 3;
console.log(x);
x *= 2; // x = x * 2;
console.log(x);
x /= 4;  // x = x/4;
console.log(x);
x %= 4;
console.log(x);
let x1 = 90;
x1 **= 2;
console.log(x1);
console.log("New  value first is: ", x1);
x1 -= 2;
console.log("New  value is: ", x1);
x1++;
console.log("New value again is: ", x1);
